#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#

# shellcheck disable=SC2016

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m space 1 --label 1_work
yabai -m space 2 --label 2_tmp
yabai -m space 3 --label 3_media
yabai -m space 4 --label 4_webs
yabai -m space 5 --label 5_tmp
yabai -m space 6 --label 6_other
yabai -m config --space media layout float
#======= Rules =======================
yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"
yabai -m signal --add event=window_minimized active=yes action="if \$(yabai -m query --windows --window \$YABAI_WINDOW_ID | jq -r '.\"is-floating\"'); then yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null; fi"
yabai -m rule --add app="^(Calculator|System Preferences|Archive Utility|Hammerspoon|Stream|uTools|关于本机|提醒事项|系统偏好设置)$" manage=off opacity=1.00 border=off
#yabai -m rule --add app="^(Microsoft Edge|Safari浏览器)$" manage=on opacity=1.00 border=on
yabai -m rule --add app="^(Code|Obsidian|iTerm2|kitty|Alacritty)$" space=1_work
yabai -m rule --add app="^(哔哩哔哩)$" space=3_media manage=off opacity=1.00 border=off
yabai -m rule --add app="^(UU 加速器|网易云音乐)$" space=6_other manage=on opacity=1.00 border=off
#======= signal =====================
yabai -m signal --add event=application_activated app="^(Obsidian)$" action="macism com.apple.inputmethod.SCIM.ITABC"
yabai -m signal --add event=application_activated app="^(Alacritty|iTerm2|kitty|Microsoft Edge|Safari浏览器)$" action="macism com.apple.keylayout.ABC"

#yabai -m signal --add event=application_deactivated app="^(Obsidian|iTerm2|kitty)$" action="macism com.apple.keylayout.ABC"
# set special app opacity
# yabai -m signal --add event=application_activated app="^(Microsoft Edge)$" action='jq -n --argjson windows "$(yabai -m query --windows)" "\$windows[] | select(.app == \"Microsoft Edge\").id" | xargs -I{} yabai -m window {} --opacity 1.00'
# yabai -m signal --add event=application_deactivated app="^(Microsoft Edge)$" action='jq -n --argjson windows "$(yabai -m query --windows)" "\$windows[] | select(.app == \"Microsoft Edge\").id" | xargs -I{} yabai -m window {} --opacity 0.00'
# yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
# yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
# yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"
# yabai -m signal --add event=window_created action='yabai -m query --windows --window $YABAI_WINDOW_ID | jq -er ".resizable == 0 and .floating == 0" && yabai -m window $YABAI_WINDOW_ID --toggle float'
#======= config ======================
# global settings
yabai -m config \
	external_bar all:40:0 \
	mouse_follows_focus off \
	focus_follows_mouse off \
	window_placement second_child \
	window_topmost off \
	window_shadow off \
	window_animation_duration 0.22 \
	window_opacity_duration 0.22 \
	active_window_opacity 1 \
	normal_window_opacity 0.95 \
	window_opacity on \
	insert_feedback_color 0xaad75f5f \
	active_window_border_color 0xBF775759 \
	normal_window_border_color 0x7f353535 \
	window_border_width 4 \
	window_border_radius 11 \
	window_border_blur on \
	window_border_hidpi on \
	window_border on \
	split_ratio 0.50 \
	split_type auto \
	auto_balance off \
	top_padding 0 \
	left_padding 8 \
	right_padding 8 \
	bottom_padding 8 \
	window_gap 8 \
	layout bsp \
	mouse_modifier fn \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap

osascript -e 'tell application id "tracesOf.Uebersicht" to refresh widget id "simple-bar-index-jsx"'

# yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
# yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
# yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"
echo "yabai configuration loaded.."
