# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME=""

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# Caution: this setting can cause issues with multiline prompts (zsh 5.7.1 and newer seem to work)
# See https://github.com/ohmyzsh/ohmyzsh/issues/5765
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(poetry git zsh-autosuggestions zsh-vi-mode zsh-syntax-highlighting)
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)
typeset -A ZSH_HIGHLIGHT_STYLES

ZVM_VI_INSERT_ESCAPE_BINDKEY=jk
zvm_before_init() {
  local ncur=$(zvm_cursor_style $ZVM_NORMAL_MODE_CURSOR)
  local icur=$(zvm_cursor_style $ZVM_INSERT_MODE_CURSOR)

  # ZVM_INSERT_MODE_CURSOR=$icur'\e\e]12;red\a'
  # ZVM_NORMAL_MODE_CURSOR=$ncur'\e\e]12;#008800\a'
}

ZSH_HIGHLIGHT_STYLES[arg0]='fg=#dffff5,bold'
# To have paths colored instead of underlined
ZSH_HIGHLIGHT_STYLES[default]=fg=250
ZSH_HIGHLIGHT_STYLES[unknown-token]=fg=#dc7974,bold
ZSH_HIGHLIGHT_STYLES[reserved-word]=fg=108
ZSH_HIGHLIGHT_STYLES[alias]=fg=#dffff5,bold
ZSH_HIGHLIGHT_STYLES[builtin]=fg=#dffff5,bold
ZSH_HIGHLIGHT_STYLES[function]=fg=#dffff5,bold
ZSH_HIGHLIGHT_STYLES[command]=fg=#dffff5,bold
ZSH_HIGHLIGHT_STYLES[precommand]=fg=#dffff5,bold
ZSH_HIGHLIGHT_STYLES[globbing]=fg=#00bcf2,bold
ZSH_HIGHLIGHT_STYLES[path]=fg=green,underline
ZSH_HIGHLIGHT_STYLES[history-expansion]=fg=222
ZSH_HIGHLIGHT_STYLES[comment]=fg=245,italic
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]=fg=250
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]=fg=250
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]=fg=250
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]=fg=033
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]=fg=173
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]=fg=173
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]=fg=140
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]=fg=140
ZSH_HIGHLIGHT_STYLES[back-dollar-quoted-argument]=fg=140
ZSH_HIGHLIGHT_STYLES[bracket-level-1]=fg=250
ZSH_HIGHLIGHT_STYLES[bracket-level-2]=fg=250
ZSH_HIGHLIGHT_STYLES[bracket-level-3]=fg=250
ZSH_HIGHLIGHT_STYLES[bracket-level-4]=fg=250
ZSH_HIGHLIGHT_STYLES[cursor-matchingbracket]=fg=237,bold,bg=74 


ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#bac8ff,bold" #underline
#zstyle -s ':prezto:module:autosuggestions:color' found \
#  'ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE' || ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=8'
bindkey '^e' autosuggest-accept
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
source $ZSH/oh-my-zsh.sh
################# start pure ########################
# fpath+=$HOME/.zsh/pure
# autoload -U promptinit; promptinit
# # optionally define some options
# PURE_CMD_MAX_EXEC_TIME=10

# # change the path color
# zstyle :prompt:pure:path color green 
# zstyle :prompt:pure:git:branch color white

# # change the color for both `prompt:success` and `prompt:error`
# zstyle ':prompt:pure:prompt:*' color cyan 

# # turn on git stash status
# zstyle :prompt:pure:git:stash show yes
# prompt pure
################# end pure ########################
# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
source ~/.exports
source ~/.aliases
source ~/.functions
eval "$(starship init zsh)"
